<html>
    <head>
        <title>
            hey
        </title>
    </head>
        <body>
            <center>
                <h1>
                    gucci!
                    wasssup.
                </h1>
            </center>
            <h2>
                gang
            </h2>
        </body>
</html>